# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c871b36e3cedd67cc8d6eea732088ba802dcfc358b8d753424ef43a14f04d162747972b7639f05afd46747d188114dcbe90f4c4bb0c688e8ce3f308f52f87f

test:
  secret_key_base: 18fd2877c124ebad533d1315e405c1332f66dc039750e7a7523e2e4e54307b9606bafe346e85d8d079f64bb8db1352105c81ac89288cf4fad9cd52935303a107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
